[package]
name = "midi_synth"
# based on 3.3.0 of bevy_midix
version = "0.34.0"
# 0.33 -> 0.34: bevy 0.17
authors = ["dsgallups <dsgallups@protonmail.com>", "Ed Swartz"]
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[features]
defaults = ["firewheel"]
web = []
# kira = ["dep:kira", "dep:bevy_kira_audio"]
kira = []
firewheel = ["dep:firewheel", "dep:bevy_seedling"]

[dependencies]
eds_bevy_common.workspace = true

thiserror.workspace = true
anyhow.workspace = true
rand.workspace = true
# crossbeam-channel.workspace = true

rustysynth.workspace = true

xsynth-core.workspace = true
# glam.workspace = true

bevy.workspace = true

# kira = { workspace = true, optional = true }
# bevy_kira_audio = { workspace = true, optional = true }

firewheel = { workspace = true, optional = true }
bevy_seedling = { workspace = true, optional = true }

crossbeam-channel.workspace = true

wasm_thread.workspace = true
serde.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1.1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"

[dev-dependencies.bevy]
version = "0.18.0"
default-features = true
