use avian3d::math::Scalar;
use bevy::prelude::*;
use avian3d::prelude::*;

use crate::*;

pub struct CollidersPlugin;

impl Plugin for CollidersPlugin {
    fn build(&self, app: &mut App) {
        app
            .init_resource::<BaseVhacdParameters>()
            .add_systems(
                PreUpdate,
                apply_colliders,
            )
        ;
    }
}

#[derive(Resource, Reflect, Debug, Clone, Copy, PartialEq)]
#[reflect(Resource, Default)]
#[type_path = "game"]
pub struct BaseVhacdParameters {
    /// Maximum concavity.
    ///
    /// Default: 0.1 (in 2D), 0.01 (in 3D).
    /// Valid range `[0.0, 1.0]`.
    pub concavity: Scalar,
    /// Controls the bias toward clipping along symmetry planes.
    ///
    /// Default: 0.05.
    /// Valid Range: `[0.0, 1.0]`.
    pub alpha: Scalar,
    /// Controls the bias toward clipping along revolution planes.
    ///
    /// Default: 0.05.
    /// Valid Range: `[0.0, 1.0]`.
    pub beta: Scalar,
    /// Resolution used during the voxelization stage.
    ///
    /// Default: 256 (in 2D), 64 (in 3D).
    pub resolution: u32,
    /// Controls the granularity of the search for the best
    /// clipping plane during the decomposition.
    ///
    /// Default: 4
    pub plane_downsampling: u32,
    /// Controls the precision of the convex-hull generation
    /// process during the clipping plane selection stage.
    ///
    /// Default: 4
    pub convex_hull_downsampling: u32,
    /// Controls the way the input mesh or polyline is being
    /// voxelized.
    ///
    /// Default: `FillMode::FloodFill { detect_cavities: false, detect_self_intersections: false }`
    pub fill_mode: FillMode,
    /// Controls whether the convex-hull should be approximated during the decomposition stage.
    /// Setting this to `true` increases performances with a slight degradation of the decomposition
    /// quality.
    ///
    /// Default: true
    pub convex_hull_approximation: bool,
    /// Controls the max number of convex-hull generated by the convex decomposition.
    ///
    /// Default: 1024
    pub max_convex_hulls: u32,
}

impl Default for BaseVhacdParameters {
    fn default() -> Self {
        Self {
            concavity: 0.001,
            alpha: 0.01,
            beta: 0.01,
            resolution: 512,
            plane_downsampling: 4,
            convex_hull_downsampling: 4,
            fill_mode: FillMode::FloodFill{ detect_cavities: true },
            convex_hull_approximation: true,
            max_convex_hulls: 1024,
        }
    }
}

#[derive(Reflect, Debug, Clone, Copy, PartialEq)]
#[reflect(Default)]
#[type_path = "game"]
pub enum ColliderKind {
    TriMesh{ downscale: f32 },
    ConvexHull,
    VoxelizeMesh{ voxel_size: f32 },
}

impl Default for ColliderKind {
    fn default() -> Self {
        ColliderKind::TriMesh{ downscale: 1.0 }
    }
}

#[derive(Reflect, Debug, Clone)]
#[reflect(Default)]
#[type_path = "game"]
pub struct LayerConfig {
    /// Which layer the mesh lives in.
    layer: GameLayer,

    /// Which layers the mesh does *not* interact with.
    ignores: Vec<GameLayer>,
}

impl LayerConfig {
    pub fn to_collision_layers(&self) -> CollisionLayers {
        let memberships = LayerMask(self.layer.to_bits());
        let mut filters = LayerMask::ALL;
        for ign in &self.ignores {
            filters &= !ign.to_bits();
        }

        CollisionLayers { memberships, filters }
    }
}

impl Default for LayerConfig {
    fn default() -> Self {
        Self {
            layer: GameLayer::World,
            ignores: default(),
        }
    }
}

/// Marker that tells a system to generate and apply collision properties to a Mesh.
#[derive(Component, Reflect, Default, Debug, Clone)]
#[reflect(Component, Default)]
#[type_path = "game"]
pub struct EnsureCollider {
    pub kind: ColliderKind,
    pub layer_config: LayerConfig,
}

fn apply_colliders(
    mut commands: Commands,
    ensure_collider_q: Query<(Entity, &EnsureCollider)>,
    changed_collider_q: Query<Entity, Changed<EnsureCollider>>,
    // collider_q: Query<Entity, With<Collider>>,
    vhacd: Res<BaseVhacdParameters>,
    mesh_q: Query<&Mesh3d>,
    child_q: Query<&Children>,
    // xfrm_q: Query<&Transform>,
    // collider_q: Query<&EnsureCollider>,
    // mut meshes: ResMut<Assets<Mesh>>,
) {
    for (ent, spawn) in ensure_collider_q.iter() {
        if changed_collider_q.contains(ent) || vhacd.is_changed() {
            apply_collider(
                commands.entity(ent),
                &vhacd,
                spawn.kind,
                &spawn.layer_config,
                &mesh_q,
            );
        }

        for kid in child_q.iter_descendants(ent) {
            if changed_collider_q.contains(ent) || vhacd.is_changed() {
                apply_collider(
                    commands.entity(kid),
                    &vhacd,
                    spawn.kind,
                    &spawn.layer_config,
                    &mesh_q,
                );
            }
        }
    }
}

fn apply_collider(
    mut ent_commands: EntityCommands,
    vhacd: &BaseVhacdParameters,
    kind: ColliderKind,
    layer_config: &LayerConfig,
    mesh_q: &Query<&Mesh3d>,
) {
    // use avian3d::math::Vector;
    // use bevy::asset::RenderAssetUsages;

    let ent = ent_commands.id();

    match kind {
        ColliderKind::TriMesh{ downscale } => {
            if !mesh_q.contains(ent) {
                return
            }

            if downscale >= 1.0 {
                ent_commands.insert(ColliderConstructor::TrimeshFromMeshWithConfig(
                    TrimeshFlags::FIX_INTERNAL_EDGES
                ));
            } else {
                let resolution = (vhacd.resolution as f32 * downscale).ceil() as u32;
                let max_convex_hulls = (vhacd.max_convex_hulls as f32 * downscale).ceil() as u32;
                ent_commands.insert(ColliderConstructor::ConvexDecompositionFromMeshWithConfig(
                    VhacdParameters {
                        concavity: vhacd.concavity,
                        alpha: vhacd.alpha,
                        beta: vhacd.beta,
                        resolution: resolution.max(16),
                        plane_downsampling: vhacd.plane_downsampling.max(1),
                        convex_hull_downsampling: vhacd.convex_hull_downsampling.max(1),
                        fill_mode: vhacd.fill_mode.clone(),
                        convex_hull_approximation: vhacd.convex_hull_approximation,
                        max_convex_hulls: max_convex_hulls.max(16),
                    }
                ));
            }
        }
        ColliderKind::VoxelizeMesh { voxel_size } => {
            if !mesh_q.contains(ent) { return }
            ent_commands.insert(ColliderConstructor::VoxelizedTrimeshFromMesh {
                voxel_size,
                fill_mode: FillMode::FloodFill { detect_cavities: true },
            });
        }
        ColliderKind::ConvexHull => {
            if !mesh_q.contains(ent) { return }
            ent_commands.insert(ColliderConstructor::ConvexHullFromMesh);
        }
    }

    ent_commands.insert(layer_config.to_collision_layers());
    ent_commands.remove::<Collider>();
}
